#!/bin/bash



for((i=1;i<=$1;i++))
do
        sum=$[$sum+$i]
done

echo $sum
a=1
while[$a -le $1]
do
        sum2=$[sum2+$a] # sum+=a
        a=$[$a+1]   #  let a++
done

read -t 10 -p"请输入您的芳名；"name
echo "welcome, $name" 
